### PR TITLE
Added a new generic outputter and also modified error outputter

### PR DESCRIPTION
**Pull request by bhatnagarconsulting**
Hi,

I have added a new generic outputter and also modified error outputter code. Please review and approve.

Regards,
Bhatnagarconsulting (developer)

### CODE REVIEW

**Comment by shitijbhatnagar** [comment]
Hi bhatnagarconsulting(developer), please add more text in sysout. Thanks.

**Comment by bhatnagarconsulting** [comment]
Hi Lead, I have made the changes, please approve. Regards, Bhatnagarconsulting (Developer)

**Comment by shitijbhatnagar** [comment]
Code looks fine now. Regards, Lead

**Review by shitijbhatnagar — APPROVED** [review]
Reviewed and looks good from my end

**Pull request merged**
